CREATE TABLE FILM 
(
  FILM_ID NUMBER NOT NULL 
, BUDGET NUMBER NOT NULL 
, HOMEPAGE VARCHAR2(200 BYTE) 
, ORIGINAL_TITLE VARCHAR2(200 BYTE) NOT NULL 
, OVERVIEW VARCHAR2(2000 BYTE) 
, POPULARITY NUMBER 
, RELEASE_DATE DATE 
, REVENUE NUMBER 
, RUNTIME NUMBER  
, TAGLINE VARCHAR2(200 BYTE) 
, TITLE VARCHAR2(200 BYTE) 
, VOTE_AVERAGE NUMBER 
, VOTE_COUNT NUMBER 
, CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID)
);


CREATE TABLE GENRES 
(
  GENRE_ID NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) 
, CONSTRAINT GENRES_PK PRIMARY KEY (GENRE_ID)
);


CREATE TABLE KEYWORDS 
(
  KEYWORD_ID NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) 
, CONSTRAINT KEYWORDS_PK PRIMARY KEY (KEYWORD_ID)
);



CREATE TABLE PRODUCTION_COMPANY 
(
  COMPANY_ID NUMBER NOT NULL 
, NAME VARCHAR2(200 BYTE) 
, CONSTRAINT PRODUCTION_COMPANY_PK PRIMARY KEY (COMPANY_ID)
);


CREATE TABLE PRODUCTION_COUNTRY 
(
  COUNTRY_ID NUMBER NOT NULL 
, NAME VARCHAR2(100 BYTE) 
, CONSTRAINT PRODUCTION_COUNTRY_PK PRIMARY KEY 
  (COUNTRY_ID)
);


CREATE TABLE SPOKEN_LANGUAGES 
(
  LANGUAGE_ID NUMBER NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, CONSTRAINT SPOKEN_LANGUAGES_PK PRIMARY KEY 
  (LANGUAGE_ID)
);



CREATE TABLE FILM_COMPANY 
(
  FILM_ID NUMBER NOT NULL 
, COMPANY_ID NUMBER NOT NULL 
, CONSTRAINT FILM_COMPANY_PK PRIMARY KEY 
  (FILM_ID 
  , COMPANY_ID)
);

ALTER TABLE FILM_COMPANY
ADD CONSTRAINT FILM_COMPANY_COMPANY_FK FOREIGN KEY
(
  COMPANY_ID 
)
REFERENCES PRODUCTION_COMPANY
(COMPANY_ID);

ALTER TABLE FILM_COMPANY
ADD CONSTRAINT FILM_COMPANY_FILM_FK FOREIGN KEY
(
  FILM_ID 
)
REFERENCES FILM
(FILM_ID);


CREATE TABLE FILM_COUNTRY 
(
  FILM_ID NUMBER NOT NULL 
, COUNTRY_ID NUMBER NOT NULL 
, CONSTRAINT FILM_COUNTRY_PK PRIMARY KEY 
  (
    FILM_ID 
  , COUNTRY_ID 
  )
);

ALTER TABLE FILM_COUNTRY
ADD CONSTRAINT FILM_COUNTRY_COUNTRY_FK FOREIGN KEY
(
  COUNTRY_ID 
)
REFERENCES PRODUCTION_COUNTRY
(
  COUNTRY_ID 
);

ALTER TABLE FILM_COUNTRY
ADD CONSTRAINT FILM_COUNTRY_FILM_FK FOREIGN KEY
(
  FILM_ID 
)
REFERENCES FILM
(
  FILM_ID 
);


CREATE TABLE FILM_GENRE 
(
  FILM_ID NUMBER NOT NULL 
, GENRE_ID NUMBER NOT NULL 
, CONSTRAINT FILM_GENRE_PK PRIMARY KEY 
  (
    FILM_ID 
  , GENRE_ID 
  )
);

ALTER TABLE FILM_GENRE
ADD CONSTRAINT FILM_FK FOREIGN KEY
(
  FILM_ID 
)
REFERENCES FILM
(
  FILM_ID 
);

ALTER TABLE FILM_GENRE
ADD CONSTRAINT GENRE_FK FOREIGN KEY
(
  GENRE_ID 
)
REFERENCES GENRES
(
  GENRE_ID 
);


CREATE TABLE FILM_KEYWORDS 
(
  FILM_ID NUMBER NOT NULL 
, KEYWORD_ID NUMBER NOT NULL 
, CONSTRAINT FILM_KEYWORDS_PK PRIMARY KEY 
  (
    FILM_ID 
  , KEYWORD_ID 
  )
);

ALTER TABLE FILM_KEYWORDS
ADD CONSTRAINT FILM_KEYWORDS_FILM_FK FOREIGN KEY
(
  FILM_ID 
)
REFERENCES FILM
(
  FILM_ID 
);

ALTER TABLE FILM_KEYWORDS
ADD CONSTRAINT FILM_KEYWORDS_KEYWORDS_FK FOREIGN KEY
(
  KEYWORD_ID 
)
REFERENCES KEYWORDS
(
  KEYWORD_ID 
);


CREATE TABLE FILM_LANGUAGE 
(
  FILM_ID NUMBER NOT NULL 
, LANGUAGE_ID NUMBER NOT NULL 
, CONSTRAINT FILM_LANGUAGE_PK PRIMARY KEY 
  (
    FILM_ID 
  , LANGUAGE_ID 
  )
);

ALTER TABLE FILM_LANGUAGE
ADD CONSTRAINT FILM_LANGUAGE_FILM_FK FOREIGN KEY
(
  FILM_ID 
)
REFERENCES FILM
(
  FILM_ID 
);

ALTER TABLE FILM_LANGUAGE
ADD CONSTRAINT FILM_LANGUAGE_LANGUAGE_FK FOREIGN KEY
(
  LANGUAGE_ID 
)
REFERENCES SPOKEN_LANGUAGES
(
  LANGUAGE_ID 
);
